import groomers from '../constants/groomers.json';
import {
  areasForCity as sharedAreasForCity, areasOf, ratingLabel, readCityPreference, reviewLabel,
  shortServices, telHref, writeCityPreference,
} from './directory';

/* The groomer services directory. Same shape and same rules as utils/vets.js:

   `groomers.json` is generated by scripts/extract_groomers.py, which exports
   ONLY user-facing columns. Tier, Confidence Score and the "Notes" column
   are used to decide inclusion and order at build time and are then dropped,
   so they are not in the bundle and cannot be rendered by accident.
   The file arrives already ordered — do not re-sort it here.

   Tier 3 entries are not in the file at all. Only Hyderabad has data today;
   GROOMER_CITIES is derived from the file itself so a new city tab appears
   the moment the workbook is re-extracted, with no code change here. */

export const GROOMER_CITIES = [...new Set(groomers.map((g) => g.city))];

const CITY_PREF_KEY = 'pb_groomer_city';

export const groomersForCity = (city) => groomers.filter((g) => g.city === city);

export { areasOf, ratingLabel, reviewLabel, shortServices, telHref };

export const readGroomerCityPreference = () => readCityPreference(CITY_PREF_KEY, GROOMER_CITIES);
export const writeGroomerCityPreference = (city) => writeCityPreference(CITY_PREF_KEY, city);

export const areasForCity = (city) => sharedAreasForCity(groomers, city);
