import vets from '../constants/vets.json';
import {
  areasForCity as sharedAreasForCity, areasOf, ratingLabel, readCityPreference, reviewLabel,
  shortServices, telHref, writeCityPreference,
} from './directory';

/* The vet services directory.

   `vets.json` is generated by scripts/extract_vets.py, which exports ONLY
   user-facing columns. Tier, Confidence Score and the "Notes / Red Flags"
   column are used to decide inclusion and order at build time and are then
   dropped, so they are not in the bundle and cannot be rendered by accident.
   The file arrives already ordered — do not re-sort it here.

   Tier 3 entries are not in the file at all. Formatting/city-preference
   helpers shared with the groomer directory live in utils/directory.js. */

export const VET_CITIES = ['Hyderabad', 'Chennai', 'Bangalore', 'Pune', 'Mumbai'];

const CITY_PREF_KEY = 'pb_vet_city';

export const vetsForCity = (city) => vets.filter((v) => v.city === city);

export const allVetCities = () => VET_CITIES.filter((c) => vets.some((v) => v.city === c));

export { areasOf, ratingLabel, reviewLabel, shortServices, telHref };

export const readVetCityPreference = () => readCityPreference(CITY_PREF_KEY, VET_CITIES);
export const writeVetCityPreference = (city) => writeCityPreference(CITY_PREF_KEY, city);

export const areasForCity = (city) => sharedAreasForCity(vets, city);
